export enum RoomEventTypeEnum {
    JOIN_ROOM = "JOIN_ROOM",
    LEAVE_ROOM = "LEAVE_ROOM",
    GAME_START = "GAME_START",
    VALID_MOVE = "VALID_MOVE",
    INVALID_MOVE = "INVALID_MOVE",
    WIN_LOCAL_BOARD = "WIN_LOCAL_BOARD",
    GAME_ENDS = "GAME_ENDS",
}
